# Generated by Django 3.2.6 on 2021-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210807_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='header_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
