# Generated by Django 3.2.6 on 2021-08-07 20:25

# import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            # field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
            field=models.TextField(),
        ),
    ]
