# Generated by Django 3.2.6 on 2021-08-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
