# Generated by Django 3.2.6 on 2021-08-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='header_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
    ]
