# Generated by Django 3.2.5 on 2021-08-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210807_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='ENGcontent',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ESPcontent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
