# Generated by Django 3.2.5 on 2021-08-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210809_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='ENGcontent',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='ESPcontent',
        ),
    ]
