# Generated by Django 3.2.5 on 2021-08-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(help_text='Recommended Width=200 Height=250', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
